package POJO;
// Generated 23-ene-2019 16:14:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private String tipoIdentificador;
     private String identifcador;
     private String nombre;
     private String apellido;
     private String email;
     private Integer telefono;
     private String contrasena;
     private Set tarjetas = new HashSet(0);

    public Cliente() {
    }

    public Cliente(String tipoIdentificador, String identifcador, String nombre, String apellido, String email, Integer telefono, String contrasena, Set tarjetas) {
       this.tipoIdentificador = tipoIdentificador;
       this.identifcador = identifcador;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.telefono = telefono;
       this.contrasena = contrasena;
       this.tarjetas = tarjetas;
    }
    public Cliente(String tipoIdentificador, String identifcador, String nombre, String apellido, String email, Integer telefono) {
       this.tipoIdentificador = tipoIdentificador;
       this.identifcador = identifcador;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.telefono = telefono;
    }
    public Cliente(String tipoIdentificador, String identifcador, String nombre, String apellido, String email, Integer telefono,String contrasena) {
       this.tipoIdentificador = tipoIdentificador;
       this.identifcador = identifcador;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.telefono = telefono;
       this.contrasena = contrasena;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTipoIdentificador() {
        return this.tipoIdentificador;
    }
    
    public void setTipoIdentificador(String tipoIdentificador) {
        this.tipoIdentificador = tipoIdentificador;
    }
    public String getIdentifcador() {
        return this.identifcador;
    }
    
    public void setIdentifcador(String identifcador) {
        this.identifcador = identifcador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set getTarjetas() {
        return this.tarjetas;
    }
    
    public void setTarjetas(Set tarjetas) {
        this.tarjetas = tarjetas;
    }
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjetas.add(tarjeta);
    }




}


