package POJO;
// Generated 23-ene-2019 16:14:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estacion generated by hbm2java
 */
public class Estacion  implements java.io.Serializable {


     private Integer id;
     private Integer numero;
     private String nombre;
     private String direccion;
     private Set rutasForEstacionOrigen = new HashSet(0);
     private Set rutasForEstacionDestino = new HashSet(0);

    public Estacion() {
    }

    public Estacion(Integer numero, String nombre, String direccion, Set rutasForEstacionOrigen, Set rutasForEstacionDestino) {
       this.numero = numero;
       this.nombre = nombre;
       this.direccion = direccion;
       this.rutasForEstacionOrigen = rutasForEstacionOrigen;
       this.rutasForEstacionDestino = rutasForEstacionDestino;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getRutasForEstacionOrigen() {
        return this.rutasForEstacionOrigen;
    }
    
    public void setRutasForEstacionOrigen(Set rutasForEstacionOrigen) {
        this.rutasForEstacionOrigen = rutasForEstacionOrigen;
    }
    public Set getRutasForEstacionDestino() {
        return this.rutasForEstacionDestino;
    }
    
    public void setRutasForEstacionDestino(Set rutasForEstacionDestino) {
        this.rutasForEstacionDestino = rutasForEstacionDestino;
    }




}


