package POJO;
// Generated 23-ene-2019 16:14:24 by Hibernate Tools 4.3.1



/**
 * Ocupacion generated by hbm2java
 */
public class Ocupacion  implements java.io.Serializable {


     private Integer id;
     private Reserva reserva;
     private Viajero viajero;
     private Integer asiento;
     private Double importe;

    public Ocupacion() {
    }

    public Ocupacion(Reserva reserva, Viajero viajero, Integer asiento, Double importe) {
       this.reserva = reserva;
       this.viajero = viajero;
       this.asiento = asiento;
       this.importe = importe;
    }
    public Ocupacion(Integer asiento) {
       
       this.asiento = asiento;
       
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public Viajero getViajero() {
        return this.viajero;
    }
    
    public void setViajero(Viajero viajero) {
        this.viajero = viajero;
    }
    public Integer getAsiento() {
        return this.asiento;
    }
    
    public void setAsiento(Integer asiento) {
        this.asiento = asiento;
    }
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }




}


