package POJO;
// Generated 23-ene-2019 16:14:24 by Hibernate Tools 4.3.1



/**
 * OcupacionBackup generated by hbm2java
 */
public class OcupacionBackup  implements java.io.Serializable {


     private int id;
     private ReservaBackup reservaBackup;
     private ViajeroBackup viajeroBackup;
     private Integer asiento;
     private Double importe;

    public OcupacionBackup() {
    }

	
    public OcupacionBackup(int id) {
        this.id = id;
    }
    public OcupacionBackup(int id, ReservaBackup reservaBackup, ViajeroBackup viajeroBackup, Integer asiento, Double importe) {
       this.id = id;
       this.reservaBackup = reservaBackup;
       this.viajeroBackup = viajeroBackup;
       this.asiento = asiento;
       this.importe = importe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ReservaBackup getReservaBackup() {
        return this.reservaBackup;
    }
    
    public void setReservaBackup(ReservaBackup reservaBackup) {
        this.reservaBackup = reservaBackup;
    }
    public ViajeroBackup getViajeroBackup() {
        return this.viajeroBackup;
    }
    
    public void setViajeroBackup(ViajeroBackup viajeroBackup) {
        this.viajeroBackup = viajeroBackup;
    }
    public Integer getAsiento() {
        return this.asiento;
    }
    
    public void setAsiento(Integer asiento) {
        this.asiento = asiento;
    }
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }




}


