package POJO;
// Generated 23-ene-2019 16:14:24 by Hibernate Tools 4.3.1



/**
 * Parametros generated by hbm2java
 */
public class Parametros  implements java.io.Serializable {


     private Integer id;
     private String cif;
     private String nombre;
     private String telefono;
     private String direccion;
     private String logo;
     private Integer numPlazas;

    public Parametros() {
    }

    public Parametros(String cif, String nombre, String telefono, String direccion, String logo, Integer numPlazas) {
       this.cif = cif;
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
       this.logo = logo;
       this.numPlazas = numPlazas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCif() {
        return this.cif;
    }
    
    public void setCif(String cif) {
        this.cif = cif;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public Integer getNumPlazas() {
        return this.numPlazas;
    }
    
    public void setNumPlazas(Integer numPlazas) {
        this.numPlazas = numPlazas;
    }




}


