package POJO;
// Generated 23-ene-2019 16:14:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ReservaBackup generated by hbm2java
 */
public class ReservaBackup  implements java.io.Serializable {


     private int id;
     private Tarjeta tarjeta;
     private Viaje viaje;
     private Integer localizador;
     private Double precio;
     private Date fechaPago;
     private Integer numViajeros;
     private Set ocupacionBackups = new HashSet(0);

    public ReservaBackup() {
    }

	
    public ReservaBackup(int id) {
        this.id = id;
    }
    public ReservaBackup(int id, Tarjeta tarjeta, Viaje viaje, Integer localizador, Double precio, Date fechaPago, Integer numViajeros, Set ocupacionBackups) {
       this.id = id;
       this.tarjeta = tarjeta;
       this.viaje = viaje;
       this.localizador = localizador;
       this.precio = precio;
       this.fechaPago = fechaPago;
       this.numViajeros = numViajeros;
       this.ocupacionBackups = ocupacionBackups;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public Viaje getViaje() {
        return this.viaje;
    }
    
    public void setViaje(Viaje viaje) {
        this.viaje = viaje;
    }
    public Integer getLocalizador() {
        return this.localizador;
    }
    
    public void setLocalizador(Integer localizador) {
        this.localizador = localizador;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public Integer getNumViajeros() {
        return this.numViajeros;
    }
    
    public void setNumViajeros(Integer numViajeros) {
        this.numViajeros = numViajeros;
    }
    public Set getOcupacionBackups() {
        return this.ocupacionBackups;
    }
    
    public void setOcupacionBackups(Set ocupacionBackups) {
        this.ocupacionBackups = ocupacionBackups;
    }




}


