package POJO;
// Generated 23-ene-2019 16:14:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private String tipo;
     private Integer numero;
     private String caducidad;
     private String logoTarjeta;
     private Set reservaBackups = new HashSet(0);
     private Set reservas = new HashSet(0);

    public Tarjeta() {
    }

    public Tarjeta(Cliente cliente, String tipo, Integer numero, String caducidad, String logoTarjeta, Set reservaBackups, Set reservas) {
       this.cliente = cliente;
       this.tipo = tipo;
       this.numero = numero;
       this.caducidad = caducidad;
       this.logoTarjeta = logoTarjeta;
       this.reservaBackups = reservaBackups;
       this.reservas = reservas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getCaducidad() {
        return this.caducidad;
    }
    
    public void setCaducidad(String caducidad) {
        this.caducidad = caducidad;
    }
    public String getLogoTarjeta() {
        return this.logoTarjeta;
    }
    
    public void setLogoTarjeta(String logoTarjeta) {
        this.logoTarjeta = logoTarjeta;
    }
    public Set getReservaBackups() {
        return this.reservaBackups;
    }
    
    public void setReservaBackups(Set reservaBackups) {
        this.reservaBackups = reservaBackups;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


