package POJO;
// Generated 23-ene-2019 16:14:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ViajeBackup generated by hbm2java
 */
public class ViajeBackup  implements java.io.Serializable {


     private Integer id;
     private Horario horario;
     private Date fechaViaje;
     private Date fechaBaja;
     private Integer plazasLibres;
     private Set reservaBackups = new HashSet(0);
    public ViajeBackup() {
    }

    
    public ViajeBackup(Integer id, Horario horario, Date fechaViaje,Date fechaBaja, Integer plazasLibres, Set reservaBackups) {
       this.id = id;
       this.horario = horario;
       this.fechaViaje = fechaViaje;
       this.plazasLibres = plazasLibres;
       this.reservaBackups = reservaBackups;
       this.fechaBaja=fechaBaja;
    }
    public ViajeBackup(Horario horario, Date fechaViaje, Integer plazasLibres, Set reservaBackups) {
       
       this.horario = horario;
       this.fechaViaje = fechaViaje;
       this.plazasLibres = plazasLibres;
       this.reservaBackups = reservaBackups;
    }

    public Date getFechaBaja() {
        return fechaBaja;
    }

    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public Date getFechaViaje() {
        return this.fechaViaje;
    }
    
    public void setFechaViaje(Date fechaViaje) {
        this.fechaViaje = fechaViaje;
    }
    public Integer getPlazasLibres() {
        return this.plazasLibres;
    }
    
    public void setPlazasLibres(Integer plazasLibres) {
        this.plazasLibres = plazasLibres;
    }
    public Set getReservaBackups() {
        return this.reservaBackups;
    }
    
    public void setReservaBackups(Set reservaBackups) {
        this.reservaBackups = reservaBackups;
    }



}


