package POJO;
// Generated 23-ene-2019 16:14:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ViajeBackup generated by hbm2java
 */
public class ViajeBackup  implements java.io.Serializable {


     private int id;
     private Horario horario;
     private Date fechaViaje;
     private Integer plazasLibres;

    public ViajeBackup() {
    }

	
    public ViajeBackup(int id) {
        this.id = id;
    }
    public ViajeBackup(int id, Horario horario, Date fechaViaje, Integer plazasLibres) {
       this.id = id;
       this.horario = horario;
       this.fechaViaje = fechaViaje;
       this.plazasLibres = plazasLibres;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public Date getFechaViaje() {
        return this.fechaViaje;
    }
    
    public void setFechaViaje(Date fechaViaje) {
        this.fechaViaje = fechaViaje;
    }
    public Integer getPlazasLibres() {
        return this.plazasLibres;
    }
    
    public void setPlazasLibres(Integer plazasLibres) {
        this.plazasLibres = plazasLibres;
    }




}


