package POJO;
// Generated 23-ene-2019 16:14:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ViajeroBackup generated by hbm2java
 */
public class ViajeroBackup  implements java.io.Serializable {


     private Integer id;
     private String tipoIdentificador;
     private String identificador;
     private String nombre;
     private String apellidos;
     private Set ocupacionBackups = new HashSet(0);

    public ViajeroBackup() {
    }

	
    public ViajeroBackup(int id) {
        this.id = id;
    }
    public ViajeroBackup(Integer id, String tipoIdentificador, String identificador, String nombre, String apellidos, Set ocupacionBackups) {
       this.id = id;
       this.tipoIdentificador = tipoIdentificador;
       this.identificador = identificador;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.ocupacionBackups = ocupacionBackups;
    }
    public ViajeroBackup(String tipoIdentificador, String identificador, String nombre, String apellidos) {
       
       this.tipoIdentificador = tipoIdentificador;
       this.identificador = identificador;
       this.nombre = nombre;
       this.apellidos = apellidos;
       
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTipoIdentificador() {
        return this.tipoIdentificador;
    }
    
    public void setTipoIdentificador(String tipoIdentificador) {
        this.tipoIdentificador = tipoIdentificador;
    }
    public String getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Set getOcupacionBackups() {
        return this.ocupacionBackups;
    }
    
    public void setOcupacionBackups(Set ocupacionBackups) {
        this.ocupacionBackups = ocupacionBackups;
    }




}


